name: Build and Push Docker Image
on:
  push:
    branches:
      - main
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: okbaabdelghani/devops-lab/devops-lab-api

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          cd api
          docker compose -p ci-test up -d postgres
          docker compose -p ci-test run --rm api npm test -- --runInBand
          docker compose -p ci-test down -v
  build-and-push:
    needs: test
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: log in GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Deploy to Ubuntu
        run: |
          cd ~/devops-lab
          IMAGE_TAG=${{ github.sha }} docker compose -f compose.prod.yml pull api
          IMAGE_TAG=${{ github.sha }} docker compose -f compose.prod.yml up -d